# Generated by Django 5.1 on 2024-08-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_robot_model_number_robot_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='last_maintenance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='maintenance_due',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='robot',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
