# Generated by Django 5.1 on 2024-08-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit_profile', models.BooleanField(default=True)),
                ('can_manage_robots', models.BooleanField(default=False)),
            ],
        ),
    ]
